version: "3.7"
services:
  shortly:
    image: openjdk:8-alpine
    command: java -jar shortly.jar
    build: .
    ports:
      - "9001:9001"
    volumes:
      - ./shortly-app/target/shortly-app-0.0.1-SNAPSHOT.jar:/shortly.jar
